package com.example.techhub.common

val devIconMap = mapOf(
    // Languages
    "JavaScript" to "javascript",
    "TypeScript" to "typescript",
    "Python" to "python",
    "Ruby" to "ruby",
    "Java" to "java",
    "C" to "c",
    "CPlusPlus" to "cplusplus",
    "CSharp" to "csharp",
    "PHP" to "php",
    "Swift" to "swift",
    "Go" to "go",
    "R" to "r",
    "Scala" to "scala",
    "Rust" to "rust",
    "Kotlin" to "kotlin",
    "Dart" to "dart",
    "HTML" to "html5",
    "CSS" to "css3",
    "Shell" to "shell",
    "ObjectiveC" to "objectivec",
    "Perl" to "perl",
    "Lua" to "lua",
    "Haskell" to "haskell",
    "Groovy" to "groovy",

    // Frameworks & Libraries
    "React" to "react-original",
    "Vue" to "vuejs",
    "Angular" to "angularjs",
    "Node" to "nodejs",
    "Bootstrap" to "bootstrap",
    "Laravel" to "laravel",
    "Symfony" to "symfony-original",
    "Django" to "django",
    "Flask" to "flask-original",
    "Express" to "express-original",
    "Spring" to "spring",
    "DotNet" to "dot-net",
    "Meteor" to "meteor",
    "Rails" to "rails",

    // Tools & Databases
    "Docker" to "docker",
    "Kubernetes" to "kubernetes",
    "Git" to "git",
    "Nginx" to "nginx-original",
    "Jenkins" to "jenkins",
    "Travis" to "travis",
    "MongoDB" to "mongodb",
    "Redis" to "redis",
    "PostgreSQL" to "postgresql",
    "MySQL" to "mysql",
    "SQLite" to "sqlite",
    "Oracle" to "oracle-original",
    "SQL" to "mysql"
)