package com.example.techhub.common

object DevIconClassName {
    // Languages
    const val JavaScript = "javascript"
    const val TypeScript = "typescript"
    const val Python = "python"
    const val Ruby = "ruby"
    const val Java = "java"
    const val C = "c"
    const val CPlusPlus = "cplusplus"
    const val CSharp = "csharp"
    const val PHP = "php"
    const val Swift = "swift"
    const val Go = "go"
    const val R = "r"
    const val Scala = "scala"
    const val Rust = "rust"
    const val Kotlin = "kotlin"
    const val Dart = "dart"
    const val HTML = "html5"
    const val CSS = "css3"
    const val Shell = "shell"
    const val ObjectiveC = "objectivec"
    const val Perl = "perl"
    const val Lua = "lua"
    const val Haskell = "haskell"
    const val Groovy = "groovy"

    // Frameworks & Libraries
    const val React = "react-original"
    const val Vue = "vuejs"
    const val Angular = "angularjs"
    const val Node = "nodejs"
    const val Bootstrap = "bootstrap"
    const val Laravel = "laravel"
    const val Symfony = "symfony-original"
    const val Django = "django"
    const val Flask = "flask-original"
    const val Express = "express-original"
    const val Spring = "spring"
    const val DotNet = "dot-net"
    const val Meteor = "meteor"
    const val Rails = "rails"

    // Tools & Databases
    const val Docker = "docker"
    const val Kubernetes = "kubernetes"
    const val Git = "git"
    const val Nginx = "nginx-original"
    const val Jenkins = "jenkins"
    const val Travis = "travis"
    const val MongoDB = "mongodb"
    const val Redis = "redis"
    const val PostgreSQL = "postgresql"
    const val MySQL = "mysql"
    const val SQLite = "sqlite"
    const val Oracle = "oracle-original"
    const val SQL = "mysql"
}