name: TechHubMobile
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 1.8
          distribution: 'adopt'

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TechHubMobile.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Run tests
        run: ./gradlew test
